name: core_mixins_gen
description: Code generator for core-mixins package.
version: 1.0.0
homepage: https://github.com/LacticWhale/core_mixins_gen
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  analyzer: ^5.2.0
  basic_utils: ^5.4.0
  collection: ^1.17.0
  meta: ^1.8.0
  path: ^1.8.2
